### ISSUE TITLE
Desktop Dashboard v1

### ISSUE THREAD

**Issue by coolguy1771** [ASU-CodeDevils/mineqbe#18]
# Overview

We need a way of interacting with the backend/Minecraft server. A web front end would make it possible for users to easily manage servers.

Requirements:
- [ ] Buttons to turn on and off the server
- [ ] Be accessible to the web
- [ ] Be able to see active server state
